# Generated by Django 5.0.7 on 2024-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_name_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
