# Generated by Django 5.0.7 on 2024-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
