# Generated by Django 5.0.7 on 2024-09-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_name_product_ram_product_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speed',
        ),
    ]
